---
# File-path based labels for pull requests only

docs:
  - "README.md"
  - "QUICK_REFERENCE.md"
  - "LABELS.md"
  - "CONTRIBUTING.md"
  - "BETA.md"
  - "RELEASE.md"
  - "readme.txt"

ci:
  - ".github/**"

source:
  - "Sources/**"

swift:
  - "**/*.swift"

metal:
  - "**/*.metal"
